version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - "3387:5432"
    networks:
      - postgree-net
    volumes:
      - ./data/db:/var/lib/postgresql/data/ # persist data even if container shuts down
networks:
  postgree-net:
    external: true
